// src/utils/provinciasCiudades.ts
export const provinciasConCiudades: Record<string, string[]> = {
  Azuay: ["Cuenca", "Gualaceo", "Paute"],
  Bolívar: ["Guaranda", "San Miguel", "Echeandía"],
  Cañar: ["Azogues", "Biblián", "La Troncal"],
  Carchi: ["Tulcán", "Montúfar", "Mira"],
  Chimborazo: ["Riobamba", "Guano", "Alausí"],
  Cotopaxi: ["Latacunga", "Pujilí", "Salcedo"],
  El_Oro: ["Machala", "Santa Rosa", "Pasaje"],
  Esmeraldas: ["Esmeraldas", "Atacames", "Rioverde"],
  Galápagos: ["Puerto Ayora", "Puerto Baquerizo", "Puerto Villamil"],
  Guayas: ["Guayaquil", "Daule", "Samborondón"],
  Imbabura: ["Ibarra", "Otavalo", "Cotacachi"],
  Loja: ["Loja", "Catamayo", "Saraguro"],
  Los_Ríos: ["Babahoyo", "Quevedo", "Vinces"],
  Manabí: ["Portoviejo", "Manta", "Chone"],
  Morona_Santiago: ["Macas", "Sucúa", "Logroño"],
  Napo: ["Tena", "Archidona", "El Chaco"],
  Orellana: ["Francisco de Orellana", "Loreto", "Joya de los Sachas"],
  Pastaza: ["Puyo", "Mera", "Santa Clara"],
  Pichincha: ["Quito", "Cayambe", "Machachi"],
  Santa_Elena: ["La Libertad", "Santa Elena", "Salinas"],
  Santo_Domingo: ["Santo Domingo"],
  Sucumbíos: ["Nueva Loja", "Shushufindi", "Cascales"],
  Tungurahua: ["Ambato", "Baños", "Pelileo"],
  "Zamora_Chinchipe": ["Zamora", "Yantzaza", "El Pangui"],
};
